
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-HelpRequest-PUT-edit","number":48,"title":"Created PUT (edit) endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/48"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-HelpRequest-DELETE","number":47,"title":"Created DELETE endpoint for a specific record in HelpRequest table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/47"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-HelpRequest-GET-show","number":46,"title":"Created GET (show) endpoint for a single record in HelpRequest table","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/46"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-HelpRequest-controller","number":45,"title":"Created HelpRequestController, added GET (index) and POST (create)","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/45"},{"author":{"id":"U_kgDOBdHK8A","is_bot":false,"login":"chloeqta","name":""},"headRefName":"ct-HelpRequest-create-db","number":44,"title":"Created database table for HelpRequest","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/44"},{"author":{"id":"U_kgDOBdHtDQ","is_bot":false,"login":"Shakcmpsc","name":""},"headRefName":"Yerassyl-Organizations","number":43,"title":"Created database table for UCSBOrganization","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/43"}]
