
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team02-w24-5pm-3
owner: ucsb-cs156-w24
repo_name: team02-w24-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBdiningCommonsMenuItem-GET","number":72,"title":"Michael - Implement GET() for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/72"},{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBDiningCommonsMenuItem-PUT","number":70,"title":"Michael - Implement PUT() for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/70"},{"author":{"id":"MDQ6VXNlcjQ4MTI4MDUw","is_bot":false,"login":"bigjr-mkkong","name":"michael"},"headRefName":"michael-UCSBDiningCommonsMenuItem-DELETE","number":69,"title":"Michael - Implement DELETE() for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-w24/team02-w24-5pm-3/pull/69"}]
